from app.workflows.core import workflow, Workflow

@workflow()
def create_assistatnt_prompt(input, model=None):
    """Creates a new assistant based on the input."""
    try:
        from app.assistants.included import assistant_instructions_creator
        from app.tools.included import save_to_file, user_data_files_path
        
        wf = Workflow()

        ai_data = wf.get_assistant_output_or_raise(assistant_instructions_creator(input=input.strip(), model=model))

        wf.log_msg(
            msgTitle="Assistant instructions generated by LLM",
            msgBody=ai_data
        )

        file_name = "assistants.txt"

        save_file_result = save_to_file(user_data_files_path(file_name), ai_data + "\n\n-----\n", prepend=True)
        
        wf.log_msg(msg=save_file_result["message"])

        return wf.success_response(
            data=ai_data,
            msgBody=f"Result saved to {user_data_files_path(file_name)}"
        )
    except Exception as e:
        return wf.error_response(error=e)
