from app.workflows import workflow, Workflow
from app.tools import save_to_file, user_data_files_path
from app.assistants import analyze_situation

@workflow()
def situation_analysis(input, model=None):
    """Analyzes a given situation and provides insights."""
    try:
        wf = Workflow()
        
        ai_data = wf.get_assistant_output_or_raise(analyze_situation(input=input.strip(), model=model))

        wf.log_msg(msgTitle="Situation analysis generated by LLM", msgBody=ai_data)

        file_path = user_data_files_path("situace.txt")

        save_file_result = save_to_file(file_path, ai_data + "\n\n-----\n", prepend=True)
        
        wf.log_msg(msg=save_file_result["message"])

        return wf.success_response(
            data=ai_data,
            msgBody=f"Result saved to {file_path}"
        )
    
    except Exception as e:
        return wf.error_response(error=e)