from app.workflows.core import workflow, Workflow

@workflow()
def video_transcript_summarization(input, model=None):
    """Summarizes the transcript of a video."""
    try:
        from app.tools.included import save_to_file, user_data_files_path
        from app.assistants.included import assistant_summarize_video_transcript
        
        wf = Workflow()

        ai_data = wf.get_assistant_output_or_raise(assistant_summarize_video_transcript(input=input.strip(), model=model))
        
        wf.add_msg_to_log(msgTitle="Transcript summary generated by LLM", msgBody=ai_data)

        file_name = "video_transcript_summaries.txt"
        save_file_result = save_to_file(user_data_files_path(file_name), ai_data + "\n\n-----\n", prepend=True)
        wf.add_msg_to_log(msg=save_file_result["message"])

        return wf.success_response(
            data=ai_data,
            msgBody=f"Result saved to {user_data_files_path(file_name)}"
        )
    except Exception as e:
        return wf.error_response(error=e)