from app.workflows.core import workflow, Workflow
from app.assistants.included import assistant_writer
from app.tools.included import save_to_file, json_db_add_entry, user_data_files_path

@workflow()
def write_story(input, model=None):
    """Generates short feel-good stories."""
    try:
        wf = Workflow()
        
        story = wf.get_assistant_output_or_raise(assistant_writer(input=input.strip(), model=model))
        wf.add_msg_to_log(msgTitle="Story generated by LLM", msgBody=story)

        save_file_result = save_to_file(user_data_files_path("stories.md"), story + "\n\n-----\n", prepend=True)
        wf.add_msg_to_log(msg=save_file_result["message"])

        save_db_result = json_db_add_entry(
            db_filepath=user_data_files_path("databases/stories.json"),
            collection="entries",
            entry={"input": input.strip(), "content": story},
            add_createdat=True
        )
        wf.add_msg_to_log(msg=save_db_result["message"])

        return wf.success_response(
            data=story,
            msgBody=f"Story saved to {user_data_files_path('stories.md')}"
        )
    
    except Exception as e:
        return wf.error_response(error=e)
